set linetype 1 lc rgb color_1 
set linetype 2 lc rgb color_2 
set linetype 3 lc rgb color_3 
set linetype 4 lc rgb color_4
set linetype 5 lc rgb color_5 
set linetype 6 lc rgb color_6 
set linetype 7 lc rgb color_7 
set linetype 8 lc rgb color_8 
set linetype 9 lc rgb color_9 
set linetype 10 lc rgb color_10
set linetype 11 lc rgb color_11
set linetype 12 lc rgb color_12
